### ISSUE TITLE
看不到图片

### ISSUE THREAD

**Issue by ethan-funny** [phodal/growth-ebook#21]
Hi, 我直接进到 `chapter` 目录下看每个 `markdown` 文件，发现图片都显示不出来，比如：
![image](https://cloud.githubusercontent.com/assets/2676138/14592311/c6bdc510-054f-11e6-98f7-51b463e6bd10.png)

貌似图片路径有点不太对，比如 `assets/article/prelude/cgi-arch.gif` 是不是应该改成 `../assets/article/prelude/cgi-arch.gif` ，thanks!

**Comment by phodal** [comment]
进到目录里是看不了的——为了编译成可下载的格式。只能下载，或者在线看。

**Comment by ethan-funny** [comment]
OK，明白，谢谢！
