### ISSUE TITLE
来一打Emcas编辑器给猫猫!

### ISSUE THREAD

**Issue by ghost** [phodal/growth-ebook#22]
https://github.com/phodal/growth-ebook/search?utf8=%E2%9C%93&q=Emcas

**Comment by ghost** [comment]
还是说Ecams编辑器喵? 0w0

**Comment by phodal** [comment]
@mindcat 謝謝了

**Comment by ghost** [comment]
@phodal 可以吃喵? /w\

**Comment by phodal** [comment]
@mindcat 可以了。。。
