### ISSUE TITLE
pdf版 排版 部分代码超出范围

### ISSUE THREAD

**Issue by wuqi** [phodal/growth-ebook#29]
github不知道为啥不能提交图片...
第47页,基础知识,css部分,图31上面,代码超出页面,部分看不见

```
66页  前端后台 mvc  public ModelAndView processUserDisable(HttpServletRequest 这段也超了
68页  <h3 class="information-head"><a href="#/blog/{{slug}}
88页 // gulp-mocha needs filepaths so you can't have
108页  var currentTime = that.parser.parseTime(that.dat
```

**Comment by phodal** [comment]
@wuqi 图片应该是因为网络问题。下面的`Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.`就是上传图片用的。

问题可能不是很好解决，应该是Tex模板的问题。

**Comment by wuqi** [comment]
@phodal  应该是网络问题,传不上来,不过应该可以调整下代码格式,加断行来处理吧,markdown不是很清楚,reStructuredText 加sphinx可以这么干

**Comment by phodal** [comment]
我再看看哈

**Comment by phodal** [comment]
@wuqi 已经修复了周末看怎么上传上来
