### ISSUE TITLE
建议重新整理一下第五章所有的引用内容

### ISSUE THREAD

**Issue by kaiguo** [phodal/growth-ebook#53]
引用的内容大部分都很不通顺，只能大概猜出意思。如果是英文资料翻译过来的建议附上原文 ;)

比如下面这个：

> 避免从网上复制的内容（除非你有很多其他的内容汇总，以使它看起来不同 - 我们做头条，对我们的产品页面的新闻片段的方式） 。这当然强烈适用于在自己的网站页面以及。内容重复可以混淆搜索引擎哪些页面是权威（它也可能会导致罚款，如果你只是复制粘贴别人的内容也行） ，然后你可以有你自己的网页互相竞争排名！
> 
> 如果你必须有重复的内容，利用相对=规范，让搜索引擎知道哪个 URL 是一个他们应该被视为权威。但是，如果你的页面是另一个在网络上找到一个副本？那么开始想出一些策略来增加更多的文字和信息来区分你的网页，因为这样重复的内容是决不可能得到好的排名。

**Comment by phodal** [comment]
@kaiguo 嗯~~，我再评估一下修改哪些内容哈

不过，如果从SEO来说，因为文章的内容本身就比较多，所以影响不大。
