### ISSUE TITLE
关于使用APP的一个小idear

### ISSUE THREAD

**Issue by Pillar-Zhang** [phodal/growth-ebook#55]
首先感谢作者设计了这么棒的一个**`APP`**

可否设计一个 栏目 1，把WEB端涉及到的重要**英语词汇** 常用 名词 比如[WEB专业词汇 汇总](http://blog.163.com/hongshaoguoguo@126/blog/static/18046981201262711475031/).
                              2，主流调试的程序 的**错误代码**比如 ‘’chrome调试工具‘’ 可否整理一下 附上翻译 方便的时候可以当成工具书进行查阅。

只是一个idear。

**Comment by phodal** [comment]
回答一下哈

问题1，我之前考虑过，只是实践成本有点高
问题2，这些相关的内容都在[https://github.com/phodal/growth](https://github.com/phodal/growth) 应用里有。所以，建议使用Growth应用。
