### ISSUE TITLE
2.1.4-persistence这一张有句话好像有问题

### ISSUE THREAD

**Issue by bingwei** [phodal/growth-ebook#59]
https://github.com/phodal/growth-ebook/blob/gh-pages/chapters/2.1.4-persistence.md
尽管百科上对于搜索引擎的定义是这样的：

搜索引擎指自动从因特网搜集信息，经过一定整理以后，提供给用户进行查询的系统。
【但是这样说往得不是非常准确】。因为有相当多的网站采用了搜索引擎作为基础的存储服务架构，而且他们并非自动从互联网上搜索信息。搜索引擎应该分成三个部分来组成：more...

框住部分是不是可以改成”但是这样描述并不是非常准确“

**Comment by phodal** [comment]
@bingwei 可以直接来个PR
