### ISSUE TITLE
【pdf】建议加上一页作者的名字和这个github地址

### ISSUE THREAD

**Issue by p2227** [phodal/growth-ebook#62]
类似这样的

 ![作者名字](http://img38.ddimg.cn/imgother1/20/2/21049598_1095483.jpg)

要不然pdf在传播的时候不知道源头，不好。

**Comment by phodal** [comment]
这倒是可以考虑，不过相信未来会有纸质版的。。

**Comment by phodal** [comment]
fixed in [#368092c](https://github.com/phodal/growth-ebook/commit/368092cfbd32a44cd996e5be2e776fb5797183ad)
