### ISSUE TITLE
正文中的图片都挂了

### ISSUE THREAD

**Issue by LMkillme** [phodal/growth-ebook#64]
PDF 文档中有些地方会缺失图片和代码块，直接在 github 里面看则是所有图片都打「XX」，点击XX过去也是「page not found」。ps：写的很好

**Comment by phodal** [comment]
@LMkillme 建议是在 GitHub Pages 上阅读的，growth.md 是生成的中间文件，用于转换为 HTML、EPUB 和 PDF 等格式，用的是相对路径。

**Comment by LMkillme** [comment]
@phodal  ，谢谢，习惯性像看代码那样看了 （逃
