### ISSUE TITLE
Growth 纸质版《全栈应用开发：精益实践》，现已上市

### ISSUE THREAD

**Issue by phodal** [phodal/growth-ebook#67]
![全栈应用开发：精益实践](http://growth.phodal.com/marketing/growth-paper.jpeg)

京东：[http://item.jd.com/12195442.html](http://item.jd.com/12195442.html)

当当：[http://product.dangdang.com/25077858.html](http://product.dangdang.com/25077858.html)

亚马逊：[https://www.amazon.cn/dp/B0722YJR89](https://www.amazon.cn/dp/B0722YJR89)

感谢 @ethan-funny、@izhangzhihao、@kaiguo、@gymgle、@aidewoode、@wenzhixin、@sasuke6、@wangyufeng0615、@walterlv、@lolosssss、@NehzUx、@mikulely、@yulongjun、@PhilipTang、@ReadmeCritic、@wangcongyi、@loveisbug 等用户为 《Growth: 全栈增长工程师指南》提供反馈与修改。

感谢 @Pandoraemon、@wo0d、@ReadmeCritic、@zhangmx、@felixglow 等用户为《Growth：全栈增长工程师实战》提供了反馈与修改。

你们的名字都出现在书的感谢页面里了，谢谢大家~~

**Comment by kaiguo** [comment]
恭喜🎉

**Comment by FrankKai** [comment]
杭州西湖发来贺电！

**Comment by skyseraph** [comment]
恭喜~~

**Comment by ethan-funny** [comment]
恭喜 🎉

**Comment by sasuke6** [comment]
恭喜恭喜

**Comment by ZayneL1** [comment]
恭喜！
提醒一下，京东的链接贴错啦~


________________________________
冷子玉
fclzyy@hotmail.com

发件人： Phodal Huang<mailto:notifications@github.com>
发送时间： 2017-05-26 07:32
收件人： phodal/growth-ebook<mailto:growth-ebook@noreply.github.com>
抄送： Subscribed<mailto:subscribed@noreply.github.com>
主题： [phodal/growth-ebook] Growth 纸质版《全栈应用开发：精益实践》，现已上市 (#67)

[全栈应用开发：精益实践]<https://camo.githubusercontent.com/09366a099c504881dec8956ed5d42cd79e57d015/687474703a2f2f67726f7774682e70686f64616c2e636f6d2f6d61726b6574696e672f67726f7774682d70617065722e6a706567>

京东：https://www.amazon.cn/dp/B0722YJR89

当当：http://product.dangdang.com/25077858.html

亚马逊：https://www.amazon.cn/dp/B0722YJR89

感谢 @ethan-funny<https://github.com/ethan-funny>、@izhangzhihao<https://github.com/izhangzhihao>、@kaiguo<https://github.com/kaiguo>、@gymgle<https://github.com/gymgle>、@aidewoode<https://github.com/aidewoode>、@wenzhixin<https://github.com/wenzhixin>、@sasuke6<https://github.com/sasuke6>、@wangyufeng0615<https://github.com/wangyufeng0615>、@walterlv<https://github.com/walterlv>、@lolosssss<https://github.com/lolosssss>、@NehzUx<https://github.com/nehzux>、@mikulely<https://github.com/mikulely>、@yulongjun<https://github.com/yulongjun>、@PhilipTang<https://github.com/philiptang>、@ReadmeCritic<https://github.com/readmecritic>、@wangcongyi<https://github.com/wangcongyi>、@loveisbug<https://github.com/loveisbug> 等用户为 《Growth: 全栈增长工程师指南》提供反馈与修改。

感谢 @Pandoraemon<https://github.com/pandoraemon>、@wo0d<https://github.com/wo0d>、@ReadmeCritic<https://github.com/readmecritic>、@zhangmx<https://github.com/zhangmx>、@felixglow<https://github.com/felixglow> 等用户为《Growth：全栈增长工程师实战》提供了反馈与修改。

你们的名字都出现在书的感谢页面里了，谢谢大家~~
