### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by diabloevagto** [phodal/growth-ebook#71]
介紹 XML VS JSON 這個部份有些錯誤

`
myJSON = {"age" : 12, "name" : "Danielle"}
`

是無法丟進 JSON.parse ，所以底下的範例會錯。
要將 myJSON 在用 ` 或是 ' 包起來成為字串

fixed
`
myJSON = '{"age" : 12, "name" : "Danielle"}'
`

**Comment by phodal** [comment]
@diabloevagto feel free to give a PR
