### ISSUE TITLE
Windows下的Launcy替代品Wox

### ISSUE THREAD

**Issue by KayGuoWhu** [phodal/growth-ebook#8]
补充一个Windows下比Lanuncy功能更丰富的工具[Wox](http://www.getwox.com/)，不仅支持快速启动应用程序（用户软件、系统工具等）和常用系统操作（开关机、重启、注销等），还能快速查找磁盘文件（另一个工具Everything的支持）。
亲测好用，友情推荐！:)

**Comment by phodal** [comment]
@KayGuoWhu 好的，谢谢了哈
